resumechall/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django auth stuff
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
]

resumechall/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("resumechall.apps.public.urls", namespace="public")),
    path("accounts/", include("resumechall.apps.accounts.urls", namespace="accounts")),
]

resumechall/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name
# Create your models here.
class UserProfile(models.Model):    
    # owner of the profile
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    
    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200,blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

resumechall/apps/accounts/views.py
from django.shortcuts import render
# TemplateView is a class-based view that renders the profile template
from django.views.generic import TemplateView

# LoginRequiredMixin is a mixin that requires the user to be logged in to access the profile page
from django.contrib.auth.mixins import LoginRequiredMixin




# LoginRequiredMixin is a mixin that requires the user to be logged in to access the profile page for the ProfileView class
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

# Create your views here.

resumechall/views.py
# TemplateView is a class-based view that renders the profile template
from django.views.generic import TemplateView

# LoginRequiredMixin is a mixin that requires the user to be logged in to access the profile page
from django.contrib.auth.mixins import LoginRequiredMixin




# LoginRequiredMixin is a mixin that requires the user to be logged in to access the profile page for the ProfileView class
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

resumechall/templates/about.html
<!-- templates/about.html-->
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} About Me</title> {% endblock %}
    <style>
    </style>

</head>
<body>
    {% block content %}
    <h1 class="gallery-header">AWS Cloud Resume Challenge</h1>
    <br>
    <br>
    <p class="center-about">
        So I found this challenge from a Medium post. I had been unemployed for 4 weeks 
        and I was looking for a project to do, something to learn and add to my resume in the meantime. 
        I knew it was going to be devops plus some full-stack work, but I was eager to get into it. 
    </p>
    <p class="center-about">
        I have had a nice document store in Notion for all of my notes for work and tooling, along with some personal language learning
        goals I have been tracking. 
    
        I knew I was going to get some more experience with AWS and Python, 2 things I hadn't seriosuly worked with in a few years.
        Setting up my AWS root account, breaking out into prod and dev accounts were fairly quick, and once I had my S3 set up for document storage,
        I worked on building out a Github Action so that when I made a commit to my project, it would trigger a build and deploy to my S3 bucket.
        This work was done in a day, and then I set out on the rusty stuff: Python and Django.
    </p>
    <p class="center-about">
        Using python again was like relearning how to ride a bike. Once I got my feet back up under me, I was off to the races. 
        I had the backend built and containerized in a Docker container with a Postgres database and a Django app in a couple days.
        There were a few changes to Django that threw me for a loop, but I was good after I spent an evening reading through the docs and falling asleep
        to a 13-hour Django tutorial on YouTube. Once all the pages and backend was built, it was on to the part of IT I've
        intentionally avoided the whole time: frontend HTML/CSS and Javascript.
    </p>
    <p class="center-about">
        It's not that I don't like frontend work, it's just that I know I'm not visually creative at all. 
        You don't want me designing anything outside of something minimalistic. I can appreciate good design, but I can't do it myself. 
        I like things simple and I want them to work, but anyone can throw up a basic webpage in Arial sans serif and call it a day.
        This was designed to be a challenge, so I did want to challenge myself and have it look good. I realized early how much AI can ruin
        your ability to learn something on my own. There were tools like Webflow that allowed you to export your HTML and CSS and not 
        have to write it, aka understand what's actually happening yourself. As a security guy, I really can't let 
        nefarious activities like that slide. Plus it's not a challenge if I just click a bunch of boxes and copy off a Youtube tutorial, 
        so I decided to do it all by hand.
    </p>
    <div class='container-img-about'> 
        <img class="center-img-about" src="{% static "theme/assets/img/bill.gif" %}" alt="Bill O Reilly doing it live"> </img>
        <p class="subtext-img">Me doing it live</p>
    </div>
    <p class="center-about">
        Man, learning HTML and CSS was a beast. It was fairly simple to understand, but the amount of CMD+S, Alt-Tab, and refresh is insane.
        I definitely see the benefits of using something like Webflow in the future, but for now, I'm glad I did it all solo dolo. 
        It makes sense to understand what UI/UX actually does after all, and getting a full grasp of all moving parts.
        Learning Javascript was a bit easier, but I also wasn't trying to do anything complicated this time, though I 
        do have future plans to jazz up the photo page a bit more.
    </p>
    <p class="center-about">
        Meanwhile, during all this I'm still studying for the AWS Cloud Practicioner exam. I've been watching training videos on Youtube off and on,
        not really putting too much focus into it. 
    </p>

    <h3 class="center-about">ONE WEEK LATER</h3>
    <p class="center-about">
        Wow, I spent an incredible amount of time trying to force feed myself everything I could about Kubernetes and Helm the last couple of days.
        I finally got my local Docker K8s cluster up and running, and I was able to deploy my Django app to it. I had to learn how to use Helm to deploy
        my app to the cluster, and I had an extreme amount of errors, mostly from things not properly passing off environment varibles down the line.
        My brain is great under pressure but I feel like I just tried to swallow a star. Next up is deploying this to AWS. I haven't decided yet 
        between EKS and Farscape. I may try both just for the experience.
    </p>

    <h3 class="center-about">ANOTHER WEEK LATER</h3>
    <p class="center-about">
        I've been working on this for a month now, and I'm finally done. I've got my Django app running in a Docker container, 
        deployed to EC2, with a load balancer in front to handle all SSL requests. Trying to figure out the new application load balancers compared to the classic version
        took me way more time than I am comfortable with. For some reason using the ALB always resulted in either a 502 or a 504 error, and I had to go back and forth trying to figure out
        whether it was a route53 issue, an ALB issue, or an issue with my Docker container. Eventually I resigned to using a classic load balancer and we were up and running within 10 minutes.
        I've got a lot of work to do on the frontend in regards to design, 
        jazzing up the photo page, and adding some more features (like the "What am I listening to on Spotify" module I've slowly worked on in the background),
        but I'm happy with the progress I've made. I still now have to connect to the Postgres DB in RDS, but the Sqlite3 DB will work in the time being. 
        I've learned a lot about AWS, Python, Django, Docker, Kubernetes, Helm, and CSS.  Next up, I'm going to start studying for the AWS Solutions Architect exam.
        <br>
        <br>
        Might also just toss up my bug bounty checklist I've been building out in Notion and put it up here. Or just turn this whole thing into a blog.
        <br>
        <br>
        Thanks for checking out my cloud challenge website. 
    {% endblock %}
</body>
</html>

resumechall/templates/accounts/login.html
<!-- templates/accounts/login.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Login </title> {% endblock %}
</head>
<body>
    
    {% include 'navbar.html'%}
    {% block content %}
    <h1>Login</h1>
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
            <button type="submit">Login</button>
        </div>
    </form>
    {% endblock %}
  
</body>
</html>

resumechall/templates/accounts/logout.html
<!DOCTYPE html>
{% include 'navbar.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>You have been logged out</h1>
        <p>Thank you for visiting. You have successfully logged out.</p>
        <a href="{% url 'accounts:login' %}">Login again</a>
    </div>
</body>
</html>

resumechall/templates/accounts/profile.html
{%extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Profile </title> {% endblock %}
</head>
{% include 'navbar.html'%}


{% block content %}

<h1>
    {{user.get_full_name}} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{profile.bio|default:""}}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{website}}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>{{interest.name}} {% if not forloop.last %}, {% endif %} </span>
                {% endfor %}
        </div>

    {% endif %}
{% endwith %}

{% endblock %}

resumechall/templates/base.html
{% load static %}

<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Greg Thomas - AWS Resume Challenge {% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    {% include "navbar.html" %}
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'theme/js/scripts.js' %}"></script>
</body>
</html>

resumechall/templates/blog.html
<!-- templates/blog.html-->
{%extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Blog </title> {% endblock %}
</head>
<body>
    {% include 'navbar.html'%}
    {% block content %}
    {% endblock %}
    <h1>Hello, World!</h1>
    <p>Well lets see if this works.</p>
</body>
</html>

resumechall/templates/contact.html
<!-- templates/contact.html-->
{%extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Contact Me</title> {% endblock %}
</head>
<body>
    {% include 'navbar.html'%}
    {% block content %}
    <h2 class="contact">Contact Me</h2>
    <p class="contact-info"> 
        If you would like to get in touch with me about opportunities, please email me at:  
    </p>
    <p class="contact-info">
        <a href="mailto:hello@gregoriethomas.com">hello@gregoriethomas.com
        </a>
    </p>

    <p class="contact-info">
        I am also available on LinkedIn at:
    </p>
    <p class="contact-info"> 
        <a href="https://www.linkedin.com/in/gregoriethomas">www.linkedin.com/in/gregoriethomas</a>
    </p>
    {% endblock %}

</body>
</html>

resumechall/templates/index.html
<!-- templates/index.html-->
{% extends "base.html" %}
{% load static %}

    {% block content %}
    <style>
        .right-align {
            text-align: right; /* Right-aligns the text */
            width: calc(100% / 12 * 5); /* Makes it take up 5 out of 12 columns */
            margin-left: auto; /* Ensures that the element stays to the right */
            padding-right: 20px;
            font-size: 20px;
            padding-top: 200px;
        }

        .left-align {
            text-align: left; /* Left-aligns the text */
            width: calc(100% / 12 * 5); /* Makes it take up 5 out of 12 columns */
            margin-right: auto; /* Ensures that the element stays to the left */
            font-size: 55px;
            line-height: 55px;
            padding-top: 200px;
            position: sticky;
            padding-left: 20px;

        }
        </style>
    <section class=index-section">
        <div class="div-block-1">
             <div class="left-align">
             Hacker/<br>IT Architect<br>Photographer
             </div>
                <p class="right-align">
                New Zealand based/Chicago raised experienced Information Security and 
                Infrastructure Engineer specializing in cloud solutions, security architecture, and 
                automating resilient, high-performance systems.
                </p>
                <br>
                <br>
                <p class="left-about">...and sometimes I take pictures.
                </p>
        </div>

    {% endblock %}

resumechall/templates/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'theme/css/styles.css' %}" />
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Greg Thomas</span>
        <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'theme/assets/img/killmonger.jpg' %}" alt="..." /></span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
            {% url 'public:index' as index_url %}
            <li class="nav-item"><a class="nav-link js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{index_url}}">Home</a>  </li>
            {% url 'public:resume' as resume_url %}
            <li class="nav-item"><a class="nav-link js-scroll-trigger{% if request.path == resume_url %}active{% endif %}" href="{{resume_url}}">Resume</a></li>
            {% url 'public:about' as about_url %}
            <li class="nav-item"><a class="nav-link js-scroll-trigger{% if request.path == about_url %}active{% endif %}" href="{{about_url}}">About</a></li>
            {%url 'public:contact' as contact_url %}
            <li class="nav-item"><a class="nav-link js-scroll-trigger{% if request.path == contact_url %}active{% endif %}" href="{{contact_url}}">Contact</a></li>
            {%url 'public:photos' as photos_url%}
          <li class="nav-item"><a class="nav-link js-scroll-trigger{% if request.path == photos_url %}active{% endif %}" href="{{photos_url}}">Photos</a></li>
           <!--   {%url 'public:projects' as projects_url%}
            <li class="nav-item"><a class="nav-link js-scroll-trigger{% if request.path == projects_url %}active{% endif %}" href="{{projects_url}}">Projects</a></li> -->
        </ul>
    </div>
</nav>
<!-- 
<nav>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %} <a href="{% url 'public:index' %}"> Home </a> {% endif %} </span>
    {% url 'public:resume' as resume_url %}
    <span>{% if request.path == resume_url %}Resume{% else %} <a href="{% url 'public:resume' %}"> Resume </a> {% endif %} </span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About Me{% else %} <a href="{% url 'public:about' %}"> About Me </a> {% endif %} </span>
    {%url 'public:contact' as contact_url%}
    <span>{% if request.path == contact_url %}Contact Me{% else %} <a href="{% url 'public:contact' %}"> Contact Me </a> {% endif %}</span>
    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span>Hi {%if request.path == profile_url %} {{user.username}}
                {%else %} <a href="{{ profile_url }}">{{user.username}} </a> {% endif %}!</span>
            <span>
                <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    Logout
                </a>
                <form id="logout-form" action="{% url 'accounts:logout' %}" method="post" style="display: none;">
                    {% csrf_token %}
                </form>
            </span>
        {% else %} 
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %} 
    </span>
<nav>
    --> 

resumechall/templates/photos.html
<!-- templates/photos.html-->
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'theme/css/gallery.css' %}?v=1">
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Photo Gallery{% endblock %} </title> 
    <link rel="stylesheet" href="{% static 'theme/css/gallery.css' %}?v=1">
    <style>
        
    </style>
</head>
<body>
    {% block content %}
    <h1 class="gallery-header">Photo Gallery</h1>
<br>
<br>
    <!-- Gallery Container -->
    <div class="gallery-container">
        <div class="gallery-item">
            <img src="{% static 'theme/assets/img/DJI_0051.JPG' %}" alt="Photo 1">
            <br>
            <div class="description-gallery">
                <hr>
                <p>Cape Palliser, New Zealand 2022</p>
            </div>
        </div>
        <br>
        <br>
        <div class="gallery-item">
            <img src="{% static 'theme/assets/img/DSC03146.JPG' %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Bondi Beach, Sydney, Australia, 2024</p>
            </div>
        </div>
        <br>
        <br>
        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC04934.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Cuba Street, Wellington, New Zealand 2024</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DJI_0055.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Cape Palliser, New Zealand 2022</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DJI_0133.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Havelock, New Zealand 2023</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DJI_0160.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Nelson, New Zealand 2023</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC00980.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Island Bay, New Zealand 2023</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC00997.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Island Bay, New Zealand, 2022</p>
            </div>
        </div>


        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC01002.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Island Bay, New Zealand, 2022</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC01034.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Red Rocks, New Zealand, 2022</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC01003.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Island Bay, New Zealand, 2023</p>
            </div>
        </div>

        <div class="gallery-item">
            <img src="{% static "theme/assets/img/DSC03085.JPG" %}" alt="Photo 1">
            <div class="description">
                <hr>
                <p>Bondi Beach, Australia, 2024</p>
            </div>
        </div>
        <!-- gallery-placeholder -->
        <!-- Add more gallery items as needed -->
    </div>


    <script src="{% static "theme/js/gallery.js" %}"></script>
    {% endblock %}

</body>
</html>

resumechall/templates/projects.html
<!-- templates/projects.html-->
{%extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %} Projects </title> {% endblock %}
</head>
<body>
    {% include 'navbar.html'%}
    {% block content %}
    {% endblock %}
    <h1>Hello, World!</h1>
    <p>Well lets see if this works.</p>
</body>
</html>

resumechall/templates/resume.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% include "navbar.html" %}
    <title>Greg Thomas - Resume</title>
    <style>
        body {
            margin: 20px;
        }
        h1, h2, h3 {
            color: #2C3E50;
        }
        p {
            margin: 5px 0;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        .section {
            margin-bottom: 20px;
        }
        .contact {
            font-size: 14px;
        }
    </style>
</head>
{% block content %}
<body>
    <h2>Greg Thomas, CISSP</h2>
    <br>

    <p class=""> <a href="https://github.com/gfsincere">https://github.com/gfsincere</a></p>
    <br>

    <div class="section">
        <h3>Summary</h3>
        <p>Information Security Professional with 10+ years of experience in information security engineering and Linux system administration across various industries and environments. Skilled in vulnerability management, risk management, network security, system administration, penetration testing, and regulatory compliance.</p>
    </div>

    <div class="section">
        <h3>Skills</h3>
        <ul>
            <li><strong>Certifications:</strong> Network+, Security+, CCNA, CISSP, CISA, RHCSA, RHCE</li>
            <li><strong>Systems:</strong> Linux (Debian, RHEL, CentOS, SUSE), Windows, AWS, Azure, GCP</li>
            <li><strong>Languages:</strong> Python, Ruby, Bash, Powershell, PHP, CSS, HTML</li>
            <li><strong>Cloud/Web:</strong> Terraform, Ansible, CloudFormation, Docker, Django, React</li>
            <li><strong>Frameworks:</strong> HIPAA/HITRUST, PCI-DSS, Fedramp </li>


        </ul>
    </div>

    <br>
    <br>

    <div class="section">
        <h3>Work Experience</h3>
        <br>
        <h4>2023-Present: Human Health, Information Security Officer</h4>
        <ul>
            <li>Spearheaded and executed HIPAA Type 2 assessment, ensuring compliance with healthcare data protection.</li>
            <li>Pioneered the organization's first external penetration test to enhance cyber defenses.</li>
            <li>Developed a comprehensive security and compliance framework from inception.</li>
            <li>Streamlined operations through automation of device deployment processes.</li>
            <li>Oversaw internal IT operations and proactive threat detection.</li>
        </ul>
        <br>
        <h4>2022-2023: Lateral Security, Principal Information Security Consultant</h4>
        <ul>
            <li>Conducted security evaluations for New Zealand government agencies, identifying vulnerabilities and recommending solutions.</li>
            <li>Developed and implemented security policies to ensure compliance with industry standards.</li>
            <li>Advised clients on information security best practices, data protection, and access controls.</li>
        </ul>
        <br>

        <h4> 2019-2022: Jvion, Information Security Director</h4>
        <ul>
            <li>Built and managed an information security program protecting over 30MM+ health records.</li>
            <li>Configured Rapid7 InsightIDR SIEM across AWS and Azure environments.</li>
            <li>Deployed Microsoft Sentinel and Cloud App Security in Azure.</li>
            <li>Led a team through HITRUST certification for 4 years.</li>
            <li>Managed vulnerability and patch management programs.</li>
        </ul>
        <br>

        <h4>2016-2019: Actiance Inc., Security Operations Director</h4>
        <ul>
            <li>Developed compliant security programs in line with FFEIC and the Patriot Act.</li>
            <li>Maintained 99.99% uptime of the DR/BCP facility, managing a team of 15 members.</li>
        </ul>
        <br>

        <h4>2015-2016: McGladrey LLP/RSM International, Information Security Consultant, Senior Associate</h4>
        <ul>
            <li>Led risk advisory engagements for compliance frameworks such as PCI-DSS, ISO 27001/2, and NIST 800-53.</li>
            <li>Managed large technical security audits of virtual and physical infrastructures.</li>
        </ul>
    </div>
    <br>
    <br>
    <div class="section">
        <h3>Education</h3>
        <p><strong>Harper College</strong> - LPN (2011)</p>
        <p><strong>U.S. Marines Intelligence School</strong> - Intelligence Analyst and Interrogation Specialist (2003)</p>
    </div>
    <br>
    <div class="section">
        <h3>Contributions/Philanthropy</h3>
        <ul>
            <li>Speaker at BSides Chicago (2014) and Defcon (2018) on Hacking Diversity in the tech community.</li>
            <li>Mentor for YearUp, a program teaching IT skills to underserved communities.</li>
        </ul>
    </div>

</body>
{% endblock %}
</html>